[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
environment = "F6MJX57V1LjRHxF6a7zbJGT8MyQfYAv8jrDZ8DnXpgtV"
provider = "BfHgyDmEcrmt2GyQ1ypLcopsKUJXp4zo86y3TnKffuLz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
